services:
  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
  db:
    image: mysql:8.0
    restart: always
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '33306:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', '127.0.0.1']
      interval: 5s
      timeout: 10s
      retries: 3
  backend:
    build: .
    volumes:
      - ./dockervenv:/src/.venv
      - .:/src
    ports:
      - '8000:8000'
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      PYTHONPATH: /src
    depends_on:
      - db
      - redis

volumes:
  mysql-data:
